name: MAME-libretro Linux x86_64

on:
#  schedule:
#    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    
    steps:
    - name: Install needed packages
      run: sudo apt install build-essential mesa-common-dev binutils
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build libretro mame core
      run: |
        make -f Makefile.libretro -j8
        strip -s mame_libretro.so
        zip -9 mame_libretro.so.zip mame_libretro.so
        sha256sum mame_libretro.so.zip > mame_libretro.so.zip.sha256
    - name: Create new release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: Linux_64-bit
        prerelease: false
        title: Linux x86_64
        files: |
          mame_libretro.so.zip
          mame_libretro.so.zip.sha256
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: mame_libretro.so.zip
        path: mame_libretro.so.zip
