name: MAME-libretro macOS x86_64

on:
#  schedule:
#    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  macOS:
    name: Build for macOS
    runs-on: macos-latest
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build libretro mame core
      run: |
        make -f Makefile.libretro -j8
        strip -x mame_libretro.dylib
        zip -9 mame_libretro.dylib.zip mame_libretro.dylib
        shasum -a 256 mame_libretro.dylib.zip >  mame_libretro.dylib.zip.sha256
    - name: Create new release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: macOS-x86_64
        prerelease: false
        title: macOS x86_64
        files: |
           mame_libretro.dylib.zip
           mame_libretro.dylib.zip.sha256
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: mame_libretro.dylib.zip
        path: mame_libretro.dylib.zip
