name: MAME-libretro Windows x86_64

on:
#  schedule:
#    - cron: '0 2 * * *' # run at 2 AM UTC
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Windows:
    name: Build for Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Setup MINGW64
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: wget git make mingw-w64-x86_64-binutils mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib mingw-w64-x86_64-pkg-config mingw-w64-x86_64-python2 zip p7zip
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build libretro mame core
      env:
        MINGW64: "/mingw64"
      run: |
        make -f Makefile.libretro -j8
        strip -s mame_libretro.dll
        zip -9 mame_libretro.dll.zip mame_libretro.dll
        sha256sum mame_libretro.dll.zip > mame_libretro.dll.zip.sha256
    - name: Create new release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: Windows_64-bit
        prerelease: false
        title: Windows x86_64
        files: |
          mame_libretro.dll.zip
          mame_libretro.dll.zip.sha256
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: mame_libretro.dll.zip
        path: mame_libretro.dll.zip


